---
- name: Install python3, docker, docker-compose
  hosts: aws_webserver
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum: 
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      ansible.builtin.get_url: 
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Install docker python module
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose

- name: Add ec2-user to docker group
  hosts: aws_webserver
  become: yes
  tasks: 
    - name: Add ec2-user to docker group
      ansible.builtin.user: 
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session # because when we add ec2-user to the docker group we need to restart the session so that the action could take place.
      meta: reset_connection

- name: Start docker container
  hosts: aws_webserver
  vars_prompt:
    - name: docker_password
      prompt: Enter password for docker registry
  # vars_files: 
  #   - project-vars 
  tasks: 
    - name: copy docker compose
      copy: 
        src: ./docker-compose.yaml
        dest: /home/ec2-user/
    - name: Docker login
      docker_login: 
        registry_url: https://index.docker.io/v1/
        username: raghebb
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose: 
        project_src: /home/ec2-user   







