---
- name: Install node and npm
  hosts: aws-webserver
  become: True
  become_user: root # beacuse we can not ssh to ec2 directly using root user, so we switch after to root after the conncetion is established
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install java 8 
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools 

- name: Download and Unpack nexus Installer # best practice because root user has all permissions
  hosts: aws-webserver
  become: True
  become_user: root
  tasks:
    - name: Check if nexus folder already exists
      stat: 
        path: /opt/nexus
      register: stat_result
    - name: Download Nexus
      get_url: 
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
    - name: Untar nexus Installer
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: Find nexus folder
      find:
        paths: /opt/
        patterns: "nexus-*"
        file_type: directory
      register: find_result
    - name: Rename nexus folder
      shell: mv {{find_result.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists # skip this task if it already done

- name: Create nexus user to own nexus folder
  become: True
  become_user: root
  hosts: aws-webserver
  tasks:
    - name: Ensure group nexus exists
      group: 
        name: nexus
        state: present
    - name: Create nexus user
      user: 
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file: 
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of nexus sonatype-work
      file: 
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes    

- name: Start nexus with nexus user
  become: True
  become_user: nexus
  hosts: aws-webserver
  tasks:
    # - name: Set run_as_user variable to nexus
    #   blockinfile: # edit multiple lines in a file 
    #     path: /opt/nexus/bin/nexus.rc
    #     block: | # this '|' represnts a multi lines string
    #       run_as_user="nexus"
    - name: Set run_as_user variable to nexus
      lineinfile: # replace the run_as_user var like awk
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Start nexus
      command: /opt/nexus/bin/nexus start
      
- name: Verify nexus running
  become: True
  become_user: root
  hosts: aws-webserver
  tasks:
    - name: Check with ps
      shell: ps aux | grep nexus # similar to command module but it will let us do every thing but command is more secure
      register: app_status # registing the result of this command into a var called app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: Wait one minute
      pause: 
        minutes: 1
    - name: Check with netstat
      shell: netstat -plnt # similar to command module but it will let us do every thing but command is more secure
      register: app_status # registing the result of this command into a var called app_status
    - debug: msg={{app_status.stdout_lines}}

